let map,markers={},selectedId=null;
window.onload=()=>{initMap();loadAssets();loadAlerts();setInterval(autoRefresh,30000);setInterval(updateClock,1000);};
function initMap(){map=L.map('map',{center:[30,40],zoom:2,zoomControl:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'OSM',maxZoom:18}).addTo(map);}
function riskClass(r){return r>70?'risk-high':r>40?'risk-med':'risk-low';}
function riskBadge(r){let c=r>70?'red':r>40?'yellow':'green';return `<span class='badge ${c}'>${r}%</span>`;}
async function loadAssets(){let r=await fetch('/api/assets');let d=await r.json();renderFleet(d);updateMap(d);document.getElementById('k-assets').textContent=d.length;}
async function loadAlerts(){let r=await fetch('/api/alerts');let d=await r.json();renderAlerts(d);document.getElementById('k-alerts').textContent=d.length;}
function renderFleet(assets){let el=document.getElementById('fleet-list');el.innerHTML=assets.map(a=>`<div class='fleet-item ${a.id===selectedId?"selected":""}' onclick='selectAsset("${a.id}")'>  <div><div class='fi-name'>${a.type==='flight'?'✈':'🚢'} ${a.name}</div><div class='fi-meta'>${a.route} | ${a.status} | ${a.cargo}</div></div>  <span class='fi-risk ${riskClass(a.risk||0)}'>${a.risk||0}%</span></div>`).join('');}
function updateMap(assets){assets.forEach(a=>{let icon=L.divIcon({className:'',html:`<div style='background:${a.risk>70?'#ff4444':a.risk>40?'#ffaa00':'#00ff88'};width:14px;height:14px;border-radius:50%;border:2px solid white;'></div>`,iconSize:[14,14]});if(markers[a.id])markers[a.id].remove();let m=L.marker([a.lat,a.lon],{icon}).addTo(map);m.bindPopup(`<b>${a.name}</b><br>${a.route}<br>Risk: ${a.risk||0}%<br>Lat:${a.lat} Lon:${a.lon}`);markers[a.id]=m;});}
function renderAlerts(alerts){let el=document.getElementById('alerts-list');if(!alerts.length){el.innerHTML="<p class='muted'>No alerts</p>";return;}el.innerHTML=alerts.slice(-8).reverse().map(a=>`<div class='alert-item'>⚠ ${a.msg}<div class='alert-time'>${a.time?.substring(0,19)}</div></div>`).join('');}
async function selectAsset(id){selectedId=id;let assets=await fetch('/api/assets').then(r=>r.json());let a=assets.find(x=>x.id===id);if(!a)return;document.getElementById('detail-section').style.display='block';document.getElementById('sel-name').textContent=a.name;document.getElementById('sel-risk-badge').className='badge '+(a.risk>70?'red':a.risk>40?'yellow':'green');document.getElementById('sel-risk-badge').textContent=a.risk+'% Risk';renderFleet(assets);if(map&&markers[id])map.panTo([a.lat,a.lon]);}
function showTab(t){document.querySelectorAll('.tab-content').forEach(x=>x.style.display='none');document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.getElementById('tab-'+t).style.display='block';event.target.classList.add('active');}
async function runSimulation(){if(!selectedId)return;let r=await fetch('/api/simulate/'+selectedId,{method:'POST'});let d=await r.json();let el=document.getElementById('sim-result');el.innerHTML=`<p style='color:#7a8ba0;font-size:0.8rem;margin-bottom:8px'>Current Risk: ${d.current_risk}% | Asset: ${d.asset}</p>`+d.alternatives.map((x,i)=>`<div class='route-card ${i===0?"best":""}'><div><b>${x.name}</b>${i===0?' ⭐ BEST':''}<div style='font-size:0.75rem;color:#7a8ba0'>ETA: ${x.eta_hours}h | Weather: ${x.weather_risk}% | Fuel: ${x.fuel_delta>0?'+':''}${x.fuel_delta}%</div></div><span class='route-score'>${x.score}</span></div>`).join('');}
async function triggerDemo(){if(!selectedId)return;let r=await fetch('/api/demo/'+selectedId,{method:'POST'});let d=await r.json();alert('Disruption triggered! Risk: '+d.risk+'%');await loadAssets();await loadAlerts();}
async function getDraft(){if(!selectedId)return;let r=await fetch('/api/message/'+selectedId);let d=await r.json();document.getElementById('draft-result').innerHTML=`<div class='result-box'>${d.message}</div>`;}
async function getCompass(){if(!selectedId)return;let r=await fetch('/api/quantum/compass/'+selectedId);let d=await r.json();document.getElementById('compass-result').innerHTML=`<div class='compass-dial'><div class='compass-bearing'>${d.bearing}°</div><div class='compass-cardinal'>${d.cardinal}</div><div style='font-size:0.75rem;color:#7a8ba0'>Quantum Confidence: ${d.quantum_confidence}%</div></div><div class='compass-meta'><div class='compass-stat'><div class='stat-val'>${d.stability_index}%</div><div class='stat-lbl'>Stability</div></div><div class='compass-stat'><div class='stat-val'>${d.drift_risk}°</div><div class='stat-lbl'>Drift Risk</div></div><div class='compass-stat'><div class='stat-val'>${d.magnetic_variation}°</div><div class='stat-lbl'>Mag. Var.</div></div><div class='compass-stat'><div class='stat-val'>${d.cardinal}</div><div class='stat-lbl'>Direction</div></div></div><div style='margin-top:12px;font-size:0.82rem'><b style='color:#00d4ff'>Recommended Corridors:</b><br>${d.recommended_corridors.join('<br>')}</div>`;}
async function getWeather(){if(!selectedId)return;let assets=await fetch('/api/assets').then(r=>r.json());let a=assets.find(x=>x.id===selectedId);if(!a)return;let r=await fetch(`/api/weather/${a.lat}/${a.lon}`);let d=await r.json();let col=d.risk==='HIGH'?'#ff4444':d.risk==='MEDIUM'?'#ffaa00':'#00ff88';document.getElementById('weather-result').innerHTML=`<div class='result-box'>Position: ${d.lat}, ${d.lon}<br>Avg Wave Height: ${d.avg_wave_height_m}m<br>Risk Level: <span style='color:${col};font-weight:700'>${d.risk}</span><br>Source: ${d.source}</div>`;}
async function getDaaS(){let r=await fetch('/api/daas/insights');let d=await r.json();document.getElementById('daas-result').innerHTML=`<div class='daas-grid'><div class='daas-card'><div class='daas-val'>${d.trade_volume_index}</div><div class='daas-lbl'>Trade Index</div></div><div class='daas-card'><div class='daas-val'>${d.disruption_frequency}/day</div><div class='daas-lbl'>Disruptions</div></div><div class='daas-card'><div class='daas-val'>${d.insurance_signal.delta_30d}</div><div class='daas-lbl'>Insurance Signal</div></div><div class='daas-card'><div class='daas-val'>${d.hedge_fund_indicator.shipping_stress_index}</div><div class='daas-lbl'>Stress Index</div></div></div><div style='margin-top:10px;font-size:0.8rem;color:#7a8ba0'>Top Risk Routes: ${d.top_risk_routes.join(', ')}<br>Port Congestion — Shanghai:${d.port_congestion_map.Shanghai}% Rotterdam:${d.port_congestion_map.Rotterdam}% LA:${d.port_congestion_map.LA}%</div>`;}
async function getTurbulence(){let id=document.getElementById('turb-select').value;let r=await fetch('/api/turbulence/'+id);let d=await r.json();document.getElementById('turb-result').innerHTML=`<div style='margin-bottom:8px'><b>Current:</b> <span class='turb-level ${d.current_turbulence}'>${d.current_turbulence}</span></div><div style='font-size:0.8rem;color:#7a8ba0;margin-bottom:8px'>${d.comfort_tip}</div><div>${d.hourly_forecast.slice(0,8).map(f=>`<span class='turb-level ${f.level}'>${f.level[0]}+${f.hour}h</span>`).join('')}</div>`;}
async function trackCargo(){let id=document.getElementById('cargo-input').value||'SHP-2024-001';let r=await fetch('/api/cargo/track/'+id);let d=await r.json();let stages=['Order Placed','Warehouse Pickup','Origin Port','In Transit','Destination Port','Customs','Out for Delivery','Delivered'];document.getElementById('cargo-result').innerHTML=`<div style='font-size:0.82rem'><b>${d.shipment_id}</b> — <span style='color:#00d4ff'>${d.current_stage}</span><br><div style='margin:10px 0'>${stages.map(s=>{let done=d.completed_stages.includes(s);let curr=s===d.current_stage;return `<div class='cargo-stage'><div class='stage-dot ${curr?'current':done?'done':''}'></div>${s}</div>`;}).join('')}</div><div style='color:#7a8ba0;font-size:0.78rem'>ETA: ${d.eta} | Vessel: ${d.vessel} | ${d.origin} → ${d.destination}<br>Carbon: ${d.carbon_kg}kg CO₂</div></div>`;}
async function doRefresh(){await fetch('/api/refresh',{method:'POST'});await loadAssets();await loadAlerts();}
async function autoRefresh(){await loadAssets();await loadAlerts();}
function updateClock(){document.getElementById('clock').textContent=new Date().toUTCString().slice(0,25)+' UTC';}