
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse, FileResponse
from pathlib import Path
import random, math, datetime, asyncio, httpx, os
from dotenv import load_dotenv

load_dotenv()
app = FastAPI(title="Aero-Sea Nexus")
ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "frontend"
app.mount("/static", StaticFiles(directory=str(FRONTEND)), name="static")

VESSELS = [
  {"id":"V001","name":"Pacific Star","type":"vessel","lat":35.5,"lon":139.7,"heading":270,"speed":14,"status":"underway","route":"Tokyo-LA","cargo":"Electronics"},
  {"id":"V002","name":"Atlantic Hawk","type":"vessel","lat":51.5,"lon":-0.1,"heading":180,"speed":18,"status":"underway","route":"London-NY","cargo":"Machinery"},
  {"id":"V003","name":"Indian Breeze","type":"vessel","lat":20.0,"lon":72.8,"heading":90,"speed":12,"status":"anchored","route":"Mumbai-Dubai","cargo":"Textiles"},
  {"id":"F001","name":"BA-777","type":"flight","lat":48.8,"lon":2.3,"heading":320,"speed":890,"status":"airborne","route":"Paris-NYC","cargo":"Passengers"},
  {"id":"F002","name":"EK-201","type":"flight","lat":25.2,"lon":55.3,"heading":45,"speed":920,"status":"airborne","route":"Dubai-London","cargo":"Mixed"},
]

assets = {v["id"]: dict(v) for v in VESSELS}
alerts = []

def risk_score(lat, lon, speed, asset_type):
    base = random.uniform(20, 80)
    if asset_type == "vessel" and abs(lat) > 45: base += 20
    if speed > 800: base += 10
    return min(round(base, 1), 99)

def move_asset(a):
    r = math.radians(a["heading"])
    spd = a["speed"]
    factor = 0.01 if a["type"]=="flight" else 0.001
    a["lat"] = round(a["lat"] + math.cos(r)*spd*factor*random.uniform(0.8,1.2), 4)
    a["lon"] = round(a["lon"] + math.sin(r)*spd*factor*random.uniform(0.8,1.2), 4)
    a["heading"] = (a["heading"] + random.randint(-3,3)) % 360
    a["risk"] = risk_score(a["lat"], a["lon"], a["speed"], a["type"])
    a["updated"] = datetime.datetime.utcnow().isoformat()
    return a

@app.on_event("startup")
async def startup():
    for a in assets.values(): move_asset(a)
    asyncio.create_task(refresh_loop())

async def refresh_loop():
    while True:
        await asyncio.sleep(int(os.getenv("REFRESH_INTERVAL","30")))
        for a in assets.values(): move_asset(a)
        check_alerts()

def check_alerts():
    for a in assets.values():
        if a.get("risk",0) > 70:
            alerts.append({"id":a["id"]+"_"+datetime.datetime.utcnow().isoformat()[:19],
                "asset":a["name"],"type":a["type"],"risk":a["risk"],
                "msg":f"{a["name"]} risk {a["risk"]}% on {a["route"]}",
                "time":datetime.datetime.utcnow().isoformat()})
    while len(alerts) > 50: alerts.pop(0)

@app.get("/")
async def root(): return FileResponse(str(FRONTEND/"index.html"))

@app.get("/api/status")
async def status(): return {"status":"online","assets":len(assets),"alerts":len(alerts),"time":datetime.datetime.utcnow().isoformat()}

@app.get("/api/assets")
async def get_assets(): return list(assets.values())

@app.get("/api/alerts")
async def get_alerts(): return alerts[-20:]

@app.post("/api/refresh")
async def do_refresh():
    for a in assets.values(): move_asset(a)
    check_alerts()
    return {"refreshed":True,"time":datetime.datetime.utcnow().isoformat()}

@app.post("/api/simulate/{asset_id}")
async def simulate(asset_id: str):
    a = assets.get(asset_id)
    if not a: return {"error":"not found"}
    routes = []
    for i in range(5):
        h_offset = random.randint(-30,30)
        routes.append({"id":i+1,"name":f"Route Alt {i+1}",
            "heading":(a["heading"]+h_offset)%360,
            "eta_hours":round(random.uniform(18,96),1),
            "weather_risk":round(random.uniform(10,60),1),
            "fuel_delta":round(random.uniform(-5,15),1),
            "port_congestion":round(random.uniform(5,50),1),
            "score":round(random.uniform(50,99),1)})
    routes.sort(key=lambda x: x["score"], reverse=True)
    return {"asset":a["name"],"current_risk":a.get("risk",0),"alternatives":routes}

@app.get("/api/message/{asset_id}")
async def draft_message(asset_id: str):
    a = assets.get(asset_id)
    if not a: return {"error":"not found"}
    msg = f"""OPERATIONAL ALERT - Aero-Sea Nexus AI Negotiator
Time: {datetime.datetime.utcnow().isoformat()}
Asset: {a["name"]} | Route: {a["route"]} | Type: {a["type"].upper()}
Current Risk Score: {a.get("risk","N/A")}%
Position: {a["lat"]}N, {a["lon"]}E | Speed: {a["speed"]} {'kts' if a['type']=='vessel' else 'km/h'}

RECOMMENDED ACTION:
Route deviation advised due to elevated risk conditions.
Alternative corridor identified - ETA impact: +4.2 hours.
Warehouse buffer at destination port pre-notified.
Supplier notification drafted and pending approval.

This message was generated by Aero-Sea Nexus AI Negotiator.
Review and approve before sending."""
    return {"asset":a["name"],"message":msg,"risk":a.get("risk",0)}

@app.post("/api/demo/{asset_id}")
async def demo_disruption(asset_id: str):
    a = assets.get(asset_id)
    if not a: return {"error":"not found"}
    a["risk"] = round(random.uniform(75,99),1)
    a["status"] = "disrupted"
    alerts.append({"id":a["id"]+"_demo","asset":a["name"],"type":a["type"],
        "risk":a["risk"],"msg":f"DEMO: {a["name"]} critical disruption on {a["route"]}",
        "time":datetime.datetime.utcnow().isoformat()})
    return {"triggered":True,"asset":a["name"],"risk":a["risk"]}

@app.get("/api/quantum/compass/{asset_id}")
async def quantum_compass(asset_id: str):
    a = assets.get(asset_id)
    if not a: return {"error":"not found"}
    bearing = a["heading"]
    stability = round(random.uniform(60,99),1)
    drift = round(random.uniform(0,5),2)
    dirs = ["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"]
    cardinal = dirs[round(bearing/22.5)%16]
    corridors = [f"Corridor {chr(65+i)}: {round(bearing+random.randint(-20,20))%360} deg, Risk {round(random.uniform(10,60),1)}%" for i in range(3)]
    return {"asset":a["name"],"bearing":bearing,"cardinal":cardinal,
        "stability_index":stability,"drift_risk":drift,
        "quantum_confidence":round(random.uniform(90,99.9),2),
        "recommended_corridors":corridors,
        "magnetic_variation":round(random.uniform(-5,5),1),
        "updated":datetime.datetime.utcnow().isoformat()}

@app.get("/api/weather/{lat}/{lon}")
async def get_weather(lat: float, lon: float):
    try:
        async with httpx.AsyncClient(timeout=8) as client:
            r = await client.get(f"https://marine-api.open-meteo.com/v1/marine?latitude={lat}&longitude={lon}&hourly=wave_height,wave_direction,wave_period&forecast_days=1")
            d = r.json()
            wh = d.get("hourly",{}).get("wave_height",[0]*24)
            avg = round(sum(wh[:6])/6,2) if wh else 0
            return {"lat":lat,"lon":lon,"avg_wave_height_m":avg,"risk":"HIGH" if avg>3 else "MEDIUM" if avg>1.5 else "LOW","source":"open-meteo"}
    except: return {"lat":lat,"lon":lon,"avg_wave_height_m":1.2,"risk":"LOW","source":"fallback"}

@app.get("/api/daas/insights")
async def daas_insights():
    return {"title":"Aero-Sea Nexus Data Goldmine",
        "trade_volume_index":round(random.uniform(95,110),1),
        "disruption_frequency":round(random.uniform(3,12),1),
        "top_risk_routes":["Trans-Pacific","Asia-Europe","Gulf-Mediterranean"],
        "insurance_signal":{"category":"ELEVATED","delta_30d":"+8.3%"},
        "hedge_fund_indicator":{"shipping_stress_index":round(random.uniform(40,80),1),"trend":"rising"},
        "port_congestion_map":{"Shanghai":round(random.uniform(60,90),1),"Rotterdam":round(random.uniform(30,60),1),"LA":round(random.uniform(40,70),1)},
        "updated":datetime.datetime.utcnow().isoformat()}

@app.get("/api/turbulence/{flight_id}")
async def turbulence(flight_id: str):
    a = assets.get(flight_id)
    levels = ["SMOOTH","LIGHT","MODERATE","SEVERE"]
    forecast = [{"hour":i,"level":random.choice(levels),"probability":round(random.uniform(10,90),1)} for i in range(1,13)]
    return {"flight":a["name"] if a else flight_id,
        "current_turbulence":random.choice(levels),
        "hourly_forecast":forecast,
        "comfort_tip":"Fasten seatbelt. Best seats: 10-15 rows from front.",
        "updated":datetime.datetime.utcnow().isoformat()}

@app.get("/api/cargo/track/{shipment_id}")
async def cargo_track(shipment_id: str):
    stages = ["Order Placed","Warehouse Pickup","Origin Port","In Transit","Destination Port","Customs","Out for Delivery","Delivered"]
    idx = random.randint(2,6)
    return {"shipment_id":shipment_id,
        "current_stage":stages[idx],
        "completed_stages":stages[:idx],
        "eta":( datetime.datetime.utcnow()+datetime.timedelta(days=random.randint(1,14))).strftime("%Y-%m-%d"),
        "vessel":random.choice(["Pacific Star","Atlantic Hawk","Indian Breeze"]),
        "origin":random.choice(["Shanghai","Dubai","Hamburg"]),
        "destination":random.choice(["Los Angeles","New York","Rotterdam"]),
        "carbon_kg":round(random.uniform(50,500),1),
        "updated":datetime.datetime.utcnow().isoformat()}
